export const COPROCESSOR_SCHEMA_VERSION = '1.0.0';

export const ResultClass = Object.freeze({
  REQUIRED: 'REQUIRED',
  OPPORTUNISTIC: 'OPPORTUNISTIC',
  DEFERRED: 'DEFERRED',
});

export const ResultStatus = Object.freeze({
  SUCCESS: 'SUCCESS',
  FALLBACK: 'FALLBACK',
  FAILED: 'FAILED',
});

export const ResultDestination = Object.freeze({
  FOREGROUND: 'FOREGROUND',
  NEXT_TURN: 'NEXT_TURN',
  BACKGROUND: 'BACKGROUND',
  SETTLEMENT: 'SETTLEMENT',
  CACHE: 'CACHE',
  EVALUATION: 'EVALUATION',
});

export const Freshness = Object.freeze({
  FRESH: 'FRESH',
  STALE: 'STALE',
  INVALID: 'INVALID',
});

export const Placement = Object.freeze({
  HOT: 'HOT',
  DEEP: 'DEEP',
});

export const Capability = Object.freeze({
  STRUCTURED_EXTRACTION: 'STRUCTURED_EXTRACTION',
  SEMANTIC_JUDGMENT: 'SEMANTIC_JUDGMENT',
  CHANGE_CLASSIFICATION: 'CHANGE_CLASSIFICATION',
  PROPOSAL_REVIEW: 'PROPOSAL_REVIEW',
  CONFLICT_INTERPRETATION: 'CONFLICT_INTERPRETATION',
  LONG_CONTEXT: 'LONG_CONTEXT',
  FAST_CLASSIFICATION: 'FAST_CLASSIFICATION',
  DEEP_REASONING: 'DEEP_REASONING',
  RETRIEVAL: 'RETRIEVAL',
  GRAPH: 'GRAPH',
  TRUTH_JUDGMENT: 'TRUTH_JUDGMENT',
  RERANK: 'RERANK',
  EMBED: 'EMBED',
  REFLECTION: 'REFLECTION',
  CONSOLIDATION: 'CONSOLIDATION',
  STREAM_VERIFY: 'STREAM_VERIFY',
  COMPRESSION: 'COMPRESSION',
  CHARACTER_INFERENCE: 'CHARACTER_INFERENCE',
  EXTERNAL_GROUNDING: 'EXTERNAL_GROUNDING',
});

export const FailureCode = Object.freeze({
  MALFORMED_OUTPUT: 'MALFORMED_OUTPUT',
  SCHEMA_VALIDATION_FAILED: 'SCHEMA_VALIDATION_FAILED',
  SEMANTIC_VALIDATION_FAILED: 'SEMANTIC_VALIDATION_FAILED',
  PROVIDER_FAILURE: 'PROVIDER_FAILURE',
  DEADLINE_MISS: 'DEADLINE_MISS',
  STALE_RESULT: 'STALE_RESULT',
  INVALID_REVISION: 'INVALID_REVISION',
  CORRELATION_MISMATCH: 'CORRELATION_MISMATCH',
});

export const TelemetryEvent = Object.freeze({
  TURN_EVENT_CREATED: 'COPROCESSOR_TURN_EVENT_CREATED',
  TASK_PLANNED: 'COPROCESSOR_TASK_PLANNED',
  TASK_STARTED: 'COPROCESSOR_TASK_STARTED',
  TASK_COMPLETED: 'COPROCESSOR_TASK_COMPLETED',
  VALIDATION_FAILED: 'COPROCESSOR_VALIDATION_FAILED',
  RETRY: 'COPROCESSOR_RETRY',
  FALLBACK_USED: 'COPROCESSOR_FALLBACK_USED',
  STALE_DROPPED: 'COPROCESSOR_STALE_DROPPED',
  LATE_ROUTED: 'COPROCESSOR_LATE_ROUTED',
  GATHER_CLOSED: 'COPROCESSOR_GATHER_CLOSED',
  CONTEXT_SEALED: 'COPROCESSOR_CONTEXT_SEALED',
});
