export const COPROCESSOR_SCHEMA_VERSION = '1.0.0';

export const ResultClass = Object.freeze({ REQUIRED: 'REQUIRED', OPPORTUNISTIC: 'OPPORTUNISTIC', DEFERRED: 'DEFERRED' });
export const ResultStatus = Object.freeze({ SUCCESS: 'SUCCESS', FALLBACK: 'FALLBACK', FAILED: 'FAILED' });
export const ResultDestination = Object.freeze({ FOREGROUND: 'FOREGROUND', NEXT_TURN: 'NEXT_TURN', BACKGROUND: 'BACKGROUND', SETTLEMENT: 'SETTLEMENT', CACHE: 'CACHE', EVALUATION: 'EVALUATION' });
export const Freshness = Object.freeze({ FRESH: 'FRESH', STALE: 'STALE', INVALID: 'INVALID', FUTURE_REVISION: 'FUTURE_REVISION' });
export const Placement = Object.freeze({ HOT: 'HOT', DEEP: 'DEEP' });

export const Capability = Object.freeze({
  STRUCTURED_EXTRACTION: 'STRUCTURED_EXTRACTION',
  SEMANTIC_JUDGMENT: 'SEMANTIC_JUDGMENT',
  CHANGE_CLASSIFICATION: 'CHANGE_CLASSIFICATION',
  PROPOSAL_REVIEW: 'PROPOSAL_REVIEW',
  CONFLICT_INTERPRETATION: 'CONFLICT_INTERPRETATION',
  LONG_CONTEXT: 'LONG_CONTEXT',
  FAST_CLASSIFICATION: 'FAST_CLASSIFICATION',
  DEEP_REASONING: 'DEEP_REASONING',
  RETRIEVAL: 'RETRIEVAL',
  GRAPH: 'GRAPH',
  TRUTH_JUDGMENT: 'TRUTH_JUDGMENT',
  RERANK: 'RERANK',
  EMBED: 'EMBED',
  REFLECTION: 'REFLECTION',
  CONSOLIDATION: 'CONSOLIDATION',
  STREAM_VERIFY: 'STREAM_VERIFY',
  COMPRESSION: 'COMPRESSION',
  CHARACTER_INFERENCE: 'CHARACTER_INFERENCE',
  EXTERNAL_GROUNDING: 'EXTERNAL_GROUNDING',
});

export const FailureCode = Object.freeze({
  MALFORMED_OUTPUT: 'MALFORMED_OUTPUT',
  SCHEMA_VALIDATION_FAILED: 'SCHEMA_VALIDATION_FAILED',
  SEMANTIC_VALIDATION_FAILED: 'SEMANTIC_VALIDATION_FAILED',
  PROVIDER_FAILURE: 'PROVIDER_FAILURE',
  PROVIDER_TIMEOUT: 'PROVIDER_TIMEOUT',
  PROVIDER_UNAVAILABLE: 'PROVIDER_UNAVAILABLE',
  PROVIDER_ABORTED: 'PROVIDER_ABORTED',
  CAPABILITY_UNAVAILABLE: 'CAPABILITY_UNAVAILABLE',
  SCHEMA_INVALID: 'SCHEMA_INVALID',
  UNKNOWN_REFERENCE: 'UNKNOWN_REFERENCE',
  AUTHORITY_VIOLATION: 'AUTHORITY_VIOLATION',
  DEADLINE_MISS: 'DEADLINE_MISS',
  DEADLINE_EXPIRED: 'DEADLINE_EXPIRED',
  RETRY_EXHAUSTED: 'RETRY_EXHAUSTED',
  FALLBACK_USED: 'FALLBACK_USED',
  STALE_RESULT: 'STALE_RESULT',
  FUTURE_REVISION: 'FUTURE_REVISION',
  INVALID_REVISION: 'INVALID_REVISION',
  CORRELATION_MISMATCH: 'CORRELATION_MISMATCH',
});

export const TelemetryEvent = Object.freeze({
  TURN_EVENT_CREATED: 'COPROCESSOR_TURN_EVENT_CREATED',
  TASK_PLANNED: 'COPROCESSOR_TASK_PLANNED',
  TASK_QUEUED: 'COPROCESSOR_TASK_QUEUED',
  TASK_STARTED: 'COPROCESSOR_TASK_STARTED',
  TASK_COMPLETED: 'COPROCESSOR_TASK_COMPLETED',
  TASK_YIELD_REQUESTED: 'COPROCESSOR_TASK_YIELD_REQUESTED',
  TASK_YIELDING: 'COPROCESSOR_TASK_YIELDING',
  TASK_PARKED: 'COPROCESSOR_TASK_PARKED',
  TASK_RESUMED: 'COPROCESSOR_TASK_RESUMED',
  BATCH_PROGRESS: 'COPROCESSOR_BATCH_PROGRESS',
  CACHE_HIT: 'COPROCESSOR_CACHE_HIT',
  WARM_HIT: 'COPROCESSOR_WARM_HIT',
  WARM_MISS: 'COPROCESSOR_WARM_MISS',
  WARM_PARTIAL: 'COPROCESSOR_WARM_PARTIAL',
  RETRIEVAL_QUALITY: 'COPROCESSOR_RETRIEVAL_QUALITY',
  RESULT_ROUTED: 'COPROCESSOR_RESULT_ROUTED',
  STREAM_CLAIM_CHECKED: 'COPROCESSOR_STREAM_CLAIM_CHECKED',
  CONSOLIDATION_BACKLOG: 'COPROCESSOR_CONSOLIDATION_BACKLOG',
  PROVIDER_SELECTED: 'COPROCESSOR_PROVIDER_SELECTED',
  PROVIDER_INVOKED: 'COPROCESSOR_PROVIDER_INVOKED',
  PROVIDER_FAILED: 'COPROCESSOR_PROVIDER_FAILED',
  BATCH_SLICE: 'COPROCESSOR_BATCH_SLICE',
  GREEN_ROOM_EXPIRED: 'COPROCESSOR_GREEN_ROOM_EXPIRED',
  VALIDATION_FAILED: 'COPROCESSOR_VALIDATION_FAILED',
  RETRY: 'COPROCESSOR_RETRY',
  FALLBACK_USED: 'COPROCESSOR_FALLBACK_USED',
  STALE_DROPPED: 'COPROCESSOR_STALE_DROPPED',
  LATE_ROUTED: 'COPROCESSOR_LATE_ROUTED',
  GATHER_CLOSED: 'COPROCESSOR_GATHER_CLOSED',
  CONTEXT_SEALED: 'COPROCESSOR_CONTEXT_SEALED',
});
