import test from 'node:test';import assert from 'node:assert/strict';import {Capability,CapabilityProfileRegistry,DeterministicProviderAdapter,FailureCode,JevDecisionCore,JevProviderExecutor,ProviderAdapterRegistry,ProviderInvocationError,createJevDecisionRequest,evaluateJevInvocationGate} from '../src/coprocessor/index.js';import {getWave10Case} from '../evaluation/jev-wave10-corpus.mjs';import {qualifyJevProviderPath} from '../evaluation/jev-wave10-provider-qualification.mjs';
const fresh=x=>({sourceRevisionSet:x.request.sourceRevisionSet,worldRevision:x.request.worldRevision,sceneRevision:x.request.sceneRevision,characterStateRevision:x.request.characterStateRevision,domainRevisions:x.request.domainRevisions,freshnessToken:x.request.freshnessToken});
function rig(specs){const profiles=new CapabilityProfileRegistry(),adapters=new ProviderAdapterRegistry();for(const s of specs){profiles.register({profileId:s.profileId,workerId:'slot:'+s.profileId,providerId:s.providerId,modelId:s.modelId??'fixture-model',capabilities:[Capability.SEMANTIC_JUDGMENT],structuredOutput:true,latencyClass:'LOW',maxOutputTokens:1200});adapters.register(new DeterministicProviderAdapter({providerId:s.providerId,modelId:s.modelId??'fixture-model',capabilities:[Capability.SEMANTIC_JUDGMENT],handler:s.handler}))}return{profiles,adapters,executor:new JevProviderExecutor({profiles,adapters})}}
const valid=(x,d=x.adjudicator??x.providerA,latencyMs=12)=>({payload:d,latencyMs,usage:{prompt_tokens:120,completion_tokens:40,total_tokens:160}});
test('structured response qualification records usage and latency',async()=>{const x=getWave10Case('G02_LORE_TREE_AMBIGUITY'),q=rig([{profileId:'a-primary',providerId:'provider-a',handler:()=>valid(x)}]),r=await qualifyJevProviderPath({...q,request:x.request,currentRevisionState:fresh(x),maxProviders:1});assert.equal(r.status,'SUCCESS');assert.equal(r.execution.decision.outcome,'DECIDED');assert.equal(r.execution.providerProvenance.providerId,'provider-a');assert.equal(r.execution.providerProvenance.usage.total_tokens,160);assert.ok(r.execution.latencyMetadata.providerLatencyMs>=12)});
test('malformed output fails closed and bounded fallback recovers',async()=>{const x=getWave10Case('G03_UID_DUPLICATE'),q=rig([{profileId:'a-primary',providerId:'provider-bad',handler:()=>({text:'not-json',latencyMs:4})},{profileId:'b-secondary',providerId:'provider-good',handler:()=>valid(x,x.providerA,8)}]),r=await qualifyJevProviderPath({...q,request:x.request,currentRevisionState:fresh(x),maxProviders:2});assert.equal(r.status,'FALLBACK');assert.equal(r.attempts.length,2);assert.equal(r.attempts[0].failureCode,FailureCode.MALFORMED_OUTPUT);assert.equal(r.attempts[1].status,'SUCCESS');assert.equal(r.execution.providerProvenance.providerId,'provider-good')});
test('timeout degrades primary and bounded fallback succeeds',async()=>{const x=getWave10Case('G07_SCENE_BOUNDARY'),q=rig([{profileId:'a-primary',providerId:'provider-timeout',handler:()=>{throw new ProviderInvocationError(FailureCode.PROVIDER_TIMEOUT,'fixture timeout',{providerId:'provider-timeout'})}},{profileId:'b-secondary',providerId:'provider-good',handler:()=>valid(x,x.providerA,9)}]),r=await qualifyJevProviderPath({...q,request:x.request,currentRevisionState:fresh(x),maxProviders:2});assert.equal(r.status,'FALLBACK');assert.equal(r.attempts[0].failureCode,FailureCode.PROVIDER_TIMEOUT);assert.equal(r.attempts[1].status,'SUCCESS')});
test('provider disagreement is observable and identity grants no authority',async()=>{const x=getWave10Case('G13_PROVIDER_DISAGREEMENT'),q=rig([{profileId:'a-primary',providerId:'provider-a',handler:()=>valid(x,x.providerA,7)},{profileId:'b-secondary',providerId:'provider-b',handler:()=>valid(x,x.providerB,7)}]),request=createJevDecisionRequest(x.request),gate=evaluateJevInvocationGate(request,{currentRevisionState:fresh(x),resourceAvailable:true}),a=await q.executor.execute(request,{prefilter:gate.prefilter,profileId:'a-primary'}),b=await q.executor.execute(request,{prefilter:gate.prefilter,profileId:'b-secondary'});assert.deepEqual(a.decision.selectedOptionIds,['O_A']);assert.deepEqual(b.decision.selectedOptionIds,['O_B']);assert.notEqual(a.providerProvenance.providerId,b.providerProvenance.providerId)});
test('stale result after provider execution is rejected',async()=>{const x=getWave10Case('G02_LORE_TREE_AMBIGUITY'),q=rig([{profileId:'a-primary',providerId:'provider-a',handler:()=>valid(x,x.providerA,10)}]),core=new JevDecisionCore({providerExecutor:q.executor});let reads=0;const receipt=await core.decide(x.request,{currentRevisionState:()=>{reads++;return reads===1?fresh(x):{...fresh(x),worldRevision:x.request.worldRevision+1}}});assert.equal(receipt.outcome,'STALE');assert.equal(receipt.authorityGranted,false);assert.equal(receipt.canonicalMutation,false)});
test('late result after Context Seal is future/audit only',async()=>{const x=getWave10Case('G02_LORE_TREE_AMBIGUITY'),q=rig([{profileId:'a-primary',providerId:'provider-a',handler:()=>valid(x,x.providerA,10)}]),receipt=await new JevDecisionCore({providerExecutor:q.executor}).decide(x.request,{currentRevisionState:fresh(x),sealed:true});assert.equal(receipt.admission.late,true);assert.equal(receipt.admission.foregroundEligible,false);assert.equal(receipt.authorityGranted,false)});
test('same qualified provider is consistent on repeated independent executions',async()=>{const x=getWave10Case('G09_STATE_TRANSITION_VS_CONTRADICTION'),q=rig([{profileId:'a-primary',providerId:'provider-a',handler:()=>valid(x,x.providerA,6)}]),request=createJevDecisionRequest(x.request),gate=evaluateJevInvocationGate(request,{currentRevisionState:fresh(x),resourceAvailable:true}),selections=[];for(let i=0;i<5;i++)selections.push((await q.executor.execute(request,{prefilter:gate.prefilter,profileId:'a-primary'})).decision.selectedOptionIds.join('|'));assert.deepEqual(new Set(selections),new Set(['O_TRANSITION']))});
