import test from 'node:test';
import assert from 'node:assert/strict';
import {runIntegrationWave4Acceptance} from './integration-wave4-harness.js';
import {createPhase1ContractDeclarations} from '../src/phase1-integration-fixtures.js';
import {buildIntegrationContractMatrix,compareContractFamily,IntegrationCompatibilityStatus,IntegrationContractFamily} from '../src/integration-contract-matrix.js';
import {FrameworkKernel} from '../src/framework-kernel.js';
import {SubsystemLifecycle} from '../src/framework-contracts.js';
import {inspectServiceReadiness,DependencyReadiness} from '../src/dependency-readiness.js';
import {runEventRegistryConformance,registerRepresentativePhase1Events,createRepresentativeEvent} from '../src/event-conformance.js';
import {StructuredOutputSchemaRegistry,CoreStructuredOutputValidator,StructuredValidationCode} from '../src/structured-output-validation.js';
import {createShadowContextCandidate,compareShadowContexts,exportShadowReplay,importShadowReplay,ShadowMeasurementState} from '../src/shadow-context-scorer.js';
import {createIntegrationLaneManifest,preflightAssemblyLane,createDryAssemblyPlan,AssemblyPreflightState} from '../src/assembly-preflight.js';
import {createCoreUiFixture,CoreUiFixtureKind} from '../src/core-ui-fixtures.js';
import {createContextReceiptReadModel,isCoreReadModelFresh} from '../src/core-ui-read-models.js';
import {Phase1GateEvidenceAggregator,GateEvidenceCategory,GateEvidenceState} from '../src/phase1-gate-evidence.js';
import {evaluateFt002CorePreflight,RepresentativeWorkloadHarness,RepresentativeWorkloadMetric} from '../src/core-function-test-preflight.js';

test('Wave 4 integration acceptance closes Core-side seam without claiming live integration',()=>{const r=runIntegrationWave4Acceptance();assert.equal(r.pass,true,JSON.stringify(r.metrics,null,2));});

test('contract matrix emits only explicit compatibility states and no probable state',()=>{const m=buildIntegrationContractMatrix(createPhase1ContractDeclarations());assert.equal(m.hasMismatch,false);assert.ok(m.rows.length>=20);for(const row of m.rows)assert.ok(Object.values(IntegrationCompatibilityStatus).includes(row.status));assert.equal(JSON.stringify(m).includes('probably'),false);});

test('major contract version mismatch is deterministic MISMATCH',()=>{const d=createPhase1ContractDeclarations(),scene=structuredClone(d.scene);scene.accepted=true;const event=scene.contracts.find(x=>x.family===IntegrationContractFamily.COGNITIVE_EVENT);event.version='2.0.0';const row=compareContractFamily(IntegrationContractFamily.COGNITIVE_EVENT,d.core,scene);assert.equal(row.status,IntegrationCompatibilityStatus.MISMATCH);assert.equal(row.reason,'MAJOR_VERSION_MISMATCH');});

test('dependency readiness degrades for optional absence and recovers without Core restart',()=>{const f=new FrameworkKernel(),m=(id,extra={})=>({subsystemId:id,version:'1',owner:'T',lifecycleState:SubsystemLifecycle.EXPERIMENTAL,failureBehavior:{recovery:'WAIT',diagnostics:true},diagnostics:{snapshot:true},...extra});f.services.register(m('consumer',{optionalDependencies:['memory']}));assert.equal(inspectServiceReadiness(f,'consumer').state,DependencyReadiness.DEGRADED);f.services.register(m('memory'));assert.equal(inspectServiceReadiness(f,'consumer').state,DependencyReadiness.READY);f.services.unregister('memory');assert.equal(inspectServiceReadiness(f,'consumer').state,DependencyReadiness.DEGRADED);});

test('required dependency absence is BLOCKED, not degraded',()=>{const f=new FrameworkKernel();f.services.register({subsystemId:'consumer',version:'1',owner:'T',lifecycleState:SubsystemLifecycle.EXPERIMENTAL,requiredDependencies:['required'],failureBehavior:{recovery:'WAIT',diagnostics:true},diagnostics:{snapshot:true}});assert.equal(inspectServiceReadiness(f,'consumer').state,DependencyReadiness.BLOCKED);});

test('representative event types register without Event Spine edits and preserve identity/revisions',()=>{const f=new FrameworkKernel(),r=runEventRegistryConformance(f.events);assert.equal(Object.values(r.checks).every(Boolean),true,JSON.stringify(r.checks));});

test('unknown event major version rejects and duplicate remains idempotent',()=>{const f=new FrameworkKernel();registerRepresentativePhase1Events(f.events);const e=createRepresentativeEvent({eventType:'TURN_EVENT',eventId:'e1'});assert.equal(f.events.accept(e).duplicate,false);assert.equal(f.events.accept(e).duplicate,true);const bad=f.events.accept(createRepresentativeEvent({eventType:'TURN_EVENT',eventId:'e2',eventVersion:'9.0.0'}));assert.equal(bad.ok,false);assert.equal(bad.code,'EVENT_VERSION_INCOMPATIBLE');});

test('provider identity does not change normalized canonical contract',()=>{const reg=new StructuredOutputSchemaRegistry();reg.register({schemaId:'X',typeValidate:x=>({ok:typeof x?.value==='number'}),semanticValidate:x=>x.value>=0?{ok:true}:{ok:false,errors:['negative']},normalize:x=>({value:x.value})});const v=new CoreStructuredOutputValidator({registry:reg}),a=v.validate({schemaId:'X',providerId:'A',rawOutput:{value:2}}),b=v.validate({schemaId:'X',providerId:'B',rawOutput:'{"value":2}'});assert.deepEqual(a.normalized,b.normalized);assert.equal(a.providerId,'A');assert.equal(b.providerId,'B');});

test('structured validation failures expose retry/fallback stage and never canonical-ready',()=>{const reg=new StructuredOutputSchemaRegistry();reg.register({schemaId:'X',typeValidate:x=>({ok:typeof x?.value==='number'}),semanticValidate:x=>x.value<2?{ok:true}:{ok:false,errors:['too large']}});const v=new CoreStructuredOutputValidator({registry:reg}),parse=v.validate({schemaId:'X',rawOutput:'{'}),semantic=v.validate({schemaId:'X',rawOutput:{value:3}}),version=v.validate({schemaId:'X',schemaVersion:'2.0.0',rawOutput:{value:1}});assert.equal(parse.canonicalReady,false);assert.equal(parse.failure.failureStage,'PARSE');assert.equal(parse.failure.retryable,true);assert.equal(parse.failure.fallbackEligible,true);assert.equal(semantic.failure.failureStage,'SEMANTIC');assert.equal(version.failure.code,StructuredValidationCode.SCHEMA_VERSION_UNSUPPORTED);assert.equal(version.failure.fallbackEligible,false);});

test('shadow scorer detects false CURRENT state and leaves unavailable metric NOT_MEASURED',()=>{const expected={e:'tavern',p:'state',v:'destroyed'},falseFact={e:'blade',p:'location',v:'tavern'};const a=createShadowContextCandidate({candidateId:'a',system:'AREA52',turnId:'t',current:[expected],latencyMs:10}),n=createShadowContextCandidate({candidateId:'n',system:'NEXUS',turnId:'t',current:[expected,falseFact]});const r=compareShadowContexts({turnId:'t',nexus:n,area52:a,groundTruth:{currentFacts:[expected],relevantFacts:[expected]}});assert.equal(r.winner,null);assert.ok(r.area52Metrics.currentStateCorrectness.value>r.nexusMetrics.currentStateCorrectness.value);assert.equal(r.nexusMetrics.latencyMs.state,ShadowMeasurementState.NOT_MEASURED);assert.equal(r.nexusMetrics.latencyMs.value,null);});

test('shadow receipt replay is deterministic and remains evaluation-only',()=>{const c=createShadowContextCandidate({candidateId:'a',system:'AREA52',turnId:'t'}),n=createShadowContextCandidate({candidateId:'n',system:'NEXUS',turnId:'t'}),r=compareShadowContexts({turnId:'t',nexus:n,area52:c,groundTruth:{}}),replay=importShadowReplay(exportShadowReplay(r));assert.equal(replay.measurementState,ShadowMeasurementState.REPLAYED);assert.equal(replay.authority,'EVALUATION_ONLY');assert.equal(replay.affectsGeneration,false);});

test('stale Scene result can be excluded while current Scene revision survives seal',()=>{const receipt=evaluateFt002CorePreflight({sceneSignal:{sceneId:'s',sceneRevision:4,sourceRevisionRefs:['src@1'],activeCast:[],castObservations:[],sceneRelationship:'CONTINUES'},sceneEvent:{eventId:'current',sceneRevision:4},currentSceneRevision:4,staleSceneEvent:{eventId:'stale',sceneRevision:3},staleSceneResultRoute:{resultId:'stale-result',freshness:'STALE'},sealReceipt:{id:'seal',sceneRevision:4,sourceRevisionIds:['src@1'],admittedResultIds:[]},packet:{current:[],historical:[],unresolved:[]},ft001Expected:{}});assert.equal(receipt.checks.sceneRevisionSurvives,true);assert.equal(receipt.checks.staleSceneExcluded,true);});

test('MENTIONED_ONLY character never becomes PRESENT through Core preflight',()=>{const r=evaluateFt002CorePreflight({sceneSignal:{sceneId:'s',sceneRevision:1,sourceRevisionRefs:[],activeCast:[{characterId:'present',state:'PRESENT'}],castObservations:[{characterId:'present',state:'PRESENT'},{characterId:'mentioned',state:'MENTIONED_ONLY'}],sceneRelationship:'CONTINUES'},sceneEvent:{eventId:'e',sceneRevision:1},currentSceneRevision:1,sealReceipt:{id:'seal',sceneRevision:1,sourceRevisionIds:[],admittedResultIds:[]},packet:{current:[],historical:[],unresolved:[]},ft001Expected:{}});assert.equal(r.checks.activeCastOnlyPresent,true);assert.equal(r.checks.mentionedOnlyExcluded,true);});

test('flashback and parallel Scene semantics do not imply current/later chronology',()=>{const packet={current:[],historical:[{id:'flashback-fact'}],unresolved:[]},base={sceneEvent:{eventId:'e',sceneRevision:2},currentSceneRevision:2,sealReceipt:{id:'s',sceneRevision:2,sourceRevisionIds:[],admittedResultIds:[]},packet,ft001Expected:{}};const flash=evaluateFt002CorePreflight({...base,sceneSignal:{sceneId:'x',sceneRevision:2,sourceRevisionRefs:[],activeCast:[],castObservations:[],sceneRelationship:'FLASHBACK_OF',flashbackCurrentFactIds:['flashback-fact']}}),parallel=evaluateFt002CorePreflight({...base,sceneSignal:{sceneId:'x',sceneRevision:2,sourceRevisionRefs:[],activeCast:[],castObservations:[],sceneRelationship:'PARALLEL_TO',chronologyAssumption:null}});assert.equal(flash.checks.flashbackPreservedAsHistorical,true);assert.equal(parallel.checks.parallelDoesNotImplyLater,true);});

test('Representative workload schema preserves measurement states and has no fake aggregate RP score',()=>{const h=new RepresentativeWorkloadHarness();h.recordTurn({turnId:'t1',metrics:{[RepresentativeWorkloadMetric.CURRENT_STATE_ERRORS]:{state:'MEASURED',value:0},[RepresentativeWorkloadMetric.CALLBACK_CONTINUITY]:{state:'NOT_MEASURED',value:null}}});const r=h.report();assert.equal(r.aggregateScore,null);assert.equal(r.turns[0].metrics.callbackContinuityQuality.value,null);assert.equal(r.liveQualification,false);});

test('Core UI fixtures cover healthy, late, unresolved, degraded, validation failure and reuse states',()=>{for(const kind of Object.values(CoreUiFixtureKind)){const f=createCoreUiFixture(kind);assert.equal(f.mutationAuthority,false);assert.doesNotThrow(()=>JSON.stringify(f));}});

test('UI read model is a frozen projection and stale identity is rejected',()=>{const published={sealReceipt:{turnId:'t',id:'seal',packetId:'p',packetHash:'h',worldRevision:1,sceneRevision:2,sourceRevisionIds:['s@1'],fallbackState:'NONE'},packet:{unresolved:[],provenanceIndex:{}}},delivery={plan:{promptPlanId:'plan',generationId:'g',turnId:'t',contextSealId:'seal',sealedPacketHash:'h',modelProfileId:'m',modelProfileRevision:'1',deliveryPolicyRevision:'1',worldRevision:1,sceneRevision:2,sourceRevisionDependencies:['s@1'],sections:[],segments:[],budget:{allocated:1},ordering:[],reuseDecisions:[],cacheDecisions:[],fallbackDecisions:[],dropped:[],deferred:[],status:'READY'},integrityReceipt:{valid:true}};const model=createContextReceiptReadModel({published,delivery});assert.equal(Object.isFrozen(model),true);assert.equal(isCoreReadModelFresh(model,{contextSealId:'seal',worldRevision:1}),true);assert.equal(isCoreReadModelFresh(model,{contextSealId:'other'}),false);});

test('assembly preflight detects documented patch without mutating main',()=>{const m=createIntegrationLaneManifest({branch:'lane',acceptedSha:'sha',acceptanceRun:'run',copiedPaths:[{path:'a',sourceDigest:'A'}],integrationOnlyPatches:[{path:'a',expectedDigest:'PATCH',reason:'adapter'}]}),p=preflightAssemblyLane(m,{sourceHeadSha:'sha',sourceFiles:{a:{digest:'A'}},integrationFiles:{a:{digest:'PATCH'}}}),plan=createDryAssemblyPlan([{manifest:m,preflight:p}]);assert.equal(p.state,AssemblyPreflightState.INTEGRATION_PATCH_REQUIRED);assert.equal(plan.mainMutationAllowed,false);assert.equal(plan.blocked,false);});

test('assembly preflight rejects undocumented integration-local drift',()=>{const m=createIntegrationLaneManifest({branch:'lane',acceptedSha:'sha',acceptanceRun:'run',copiedPaths:[{path:'a',sourceDigest:'A'}]}),p=preflightAssemblyLane(m,{sourceHeadSha:'sha',sourceFiles:{a:{digest:'A'}},integrationFiles:{a:{digest:'LOCAL'}}});assert.equal(p.state,AssemblyPreflightState.CONFLICT);assert.match(p.rows[0].reason,/UNDOCUMENTED/);});

test('assembly preflight detects stale source, missing path and missing acceptance',()=>{const base={branch:'lane',acceptedSha:'sha',copiedPaths:[{path:'a',sourceDigest:'A'}]};assert.equal(preflightAssemblyLane(createIntegrationLaneManifest({...base,acceptanceRun:'r'}),{sourceHeadSha:'new',sourceFiles:{a:{digest:'A'}}}).state,AssemblyPreflightState.STALE_SOURCE);assert.equal(preflightAssemblyLane(createIntegrationLaneManifest({...base,acceptanceRun:'r'}),{sourceHeadSha:'sha',sourceFiles:{}}).state,AssemblyPreflightState.MISSING_PATH);assert.equal(preflightAssemblyLane(createIntegrationLaneManifest(base),{sourceHeadSha:'sha',sourceFiles:{a:{digest:'A'}}}).state,AssemblyPreflightState.MISSING_ACCEPTANCE);});

test('Phase 1 gate aggregator never infers PASS from missing or blocked evidence',()=>{const g=new Phase1GateEvidenceAggregator();g.record({category:GateEvidenceCategory.CI,state:GateEvidenceState.PASS});let r=g.report();assert.equal(r.gateState,GateEvidenceState.PARTIAL);g.record({category:GateEvidenceCategory.BLOCKERS,state:GateEvidenceState.BLOCKED,blockers:['live-main']});r=g.report();assert.equal(r.gateState,GateEvidenceState.BLOCKED);assert.equal(r.phase2PromotionAllowed,false);});
