import test from 'node:test';import assert from 'node:assert/strict';
import {AuthorityClass,EvidenceType,ReflectionStatus,SettlementDecisionType} from '../src/contracts.js';
import {SourceRegistry} from '../src/source-registry.js';import {LoreStudyEngine} from '../src/lore-study.js';import {Area52CognitiveCore} from '../src/cognitive-core.js';import {runWave2EmberTavernGoldenWorld} from './wave2-golden-harness.js';

test('Lore Study expands distinct knowledge forms without flattening them into claims',()=>{const registry=new SourceRegistry();registry.importSource({id:'lore:rich',sourceType:'LORE',content:'Mara, also called Red Mara, owns the Ember Tavern. The Sun Blade is silver. Only members of the Ash Guild may enter the Vault. Eris can wield the Sun Blade. The Sun Blade cannot be drawn inside the Shrine.'});const study=new LoreStudyEngine({registry}).studySource('lore:rich');assert.equal(study.aliases.length,1);assert.equal(study.aliases[0].alias,'Red Mara');assert.equal(study.properties.length,1);assert.equal(study.rules.length,1);assert.equal(study.capabilities.length,1);assert.equal(study.restrictions.length,1);assert.ok(study.relationships.some(r=>r.predicate==='owns'));assert.ok(study.claims.some(c=>c.claimType==='OWNERSHIP'));assert.equal(registry.getActiveRevision('lore:rich').exactContent.includes('Red Mara'),true);for(const item of [...study.aliases,...study.properties,...study.rules,...study.capabilities,...study.restrictions,...study.relationships,...study.claims])assert.deepEqual(item.provenance.sourceRevisionIds,['lore:rich@1']);});

test('derived identities are stable across reprocessing and semantic-preserving source edits',()=>{const core=new Area52CognitiveCore();const first=core.importAndLearn({id:'lore:stable',sourceType:'LORE',content:'Mara owns the Ember Tavern.',at:0}).result;const claimId=first.claims[0].id,stableIdentity=first.claims[0].stableIdentity;const again=core.learnSource('lore:stable').result;assert.equal(again.claims[0].id,claimId);assert.equal(again.claims[0].stableIdentity,stableIdentity);const edit=core.editAndRelearn('lore:stable','Mara owns the Ember Tavern. The Ember Tavern is ancient.');const owner=edit.relearned.result.claims.find(c=>c.predicate==='owner');assert.notEqual(owner.id,claimId);assert.equal(owner.stableIdentity,stableIdentity);assert.equal(core.registry.isArtifactValid(claimId),false);assert.equal(core.registry.isArtifactValid(owner.id),true);assert.deepEqual(owner.provenance.sourceRevisionIds,['lore:stable@2']);});

test('Lore Study supports prepare execute validate commit batch boundaries',()=>{const core=new Area52CognitiveCore();core.registry.importSource({id:'batch:a',sourceType:'LORE',content:'Mara owns the Ember Tavern.',metadata:{at:0}});core.registry.importSource({id:'batch:b',sourceType:'LORE',content:'Eris can wield the Sun Blade.',metadata:{at:0}});const batches=core.study.prepareBatch(['batch:a','batch:b'],{batchSize:1});assert.equal(batches.length,2);for(const b of batches){const ex=core.study.executeBatch(b),v=core.study.validateBatch(ex);assert.equal(v.valid,true);const committed=core.study.commitBatch(v);assert.equal(committed.length,1);}assert.ok(core.registry.listArtifacts({kind:'Capability'}).length===1);});

test('compatible multi-source evidence is corroborated and compiles once with both provenance paths',()=>{const core=new Area52CognitiveCore();const a=core.importAndLearn({id:'owner:a',sourceType:'LORE',content:'Mara owns the Ember Tavern.',at:0});const b=core.importAndLearn({id:'owner:b',sourceType:'LORE',content:'The Ember Tavern has belonged to Mara for 12 years.',at:0});assert.equal(b.decisions[0].decision,SettlementDecisionType.ACCEPT_CURRENT);const projection=core.graph.currentProjection().find(x=>x.subjectId==='ember-tavern'&&x.predicate==='owner'&&x.value==='mara');assert.ok(projection);assert.equal(projection.claimIds.length,2);const q=core.query('Mara owns the Ember Tavern',{intent:'CURRENT',anchorEntityIds:['ember-tavern','mara']});const fact=q.packet.current.find(f=>f.e==='ember-tavern'&&f.p==='owner'&&f.v==='mara');assert.ok(fact);assert.equal(fact.supportIds.length,2);assert.deepEqual(q.packet.provenanceIndex[fact.id],['owner:a@1','owner:b@1']);assert.notEqual(a.result.claims[0].id,b.result.claims[0].id);});

test('Settlement preserves legitimate conflicting evidence as UNRESOLVED with explanation',()=>{const core=new Area52CognitiveCore();core.importAndLearn({id:'destroyed',sourceType:'LORE',content:'The Sun Blade is destroyed in the fire.',at:30});const journal=core.importAndLearn({id:'journal',sourceType:'LORE',content:'A later recovered journal claims the Sun Blade survived the fire.',at:50,metadata:{claimAt:30}});const decision=journal.decisions.find(d=>d.decision===SettlementDecisionType.UNRESOLVED);assert.ok(decision);assert.match(decision.reason,/conflicting|unresolved/i);assert.equal(core.graph.currentClaims({subjectId:'sun-blade',predicate:'state'}).length,0);const unresolved=core.graph.unresolvedState('sun-blade','state');assert.ok(unresolved);assert.equal(unresolved.status,'UNRESOLVED');const q=core.query('Did the Sun Blade survive?',{intent:'CONTRADICTION',anchorEntityIds:['sun-blade']});assert.ok(q.packet.unresolved.some(f=>f.v==='destroyed'));assert.ok(q.packet.unresolved.some(f=>f.v==='survived'));});

test('temporal relationships begin end and remain historically queryable',()=>{const core=new Area52CognitiveCore();core.importAndLearn({id:'join',sourceType:'EXPERIENCE',content:'Eris joins the Ash Guild.',at:10});core.importAndLearn({id:'leave',sourceType:'EXPERIENCE',content:'Eris leaves the Ash Guild.',at:20});assert.equal(core.graph.currentClaims({subjectId:'eris',predicate:'memberOf'}).length,0);const past=core.graph.historicalClaims({subjectId:'eris',predicate:'memberOf'});assert.ok(past.some(c=>c.value==='ash-guild'&&c.temporal.validUntil===20));const transitions=core.graph.transitions('eris','memberOf');assert.deepEqual(transitions.map(t=>[t.from,t.to,t.at]),[[null,'ash-guild',10],['ash-guild',null,20]]);});

test('changed property timeline preserves intact damaged repaired destroyed history',()=>{const core=new Area52CognitiveCore();for(const [id,state,at] of [['s0','intact',0],['s1','damaged',10],['s2','repaired',20],['s3','destroyed',30]])core.importAndLearn({id,sourceType:'EXPERIENCE',content:`The Relic is ${state}.`,at});const current=core.graph.currentClaims({subjectId:'relic',predicate:'state'});assert.deepEqual(current.map(c=>c.value),['destroyed']);assert.deepEqual(core.graph.historicalClaims({subjectId:'relic',predicate:'state'}).map(c=>c.value),['intact','damaged','repaired']);assert.deepEqual(core.graph.transitions('relic','state').map(t=>t.to),['intact','damaged','repaired','destroyed']);});

test('explicit causal event evidence remains distinct and provenance-backed',()=>{const core=new Area52CognitiveCore();const learned=core.importAndLearn({id:'fire:evidence',sourceType:'EXPERIENCE',content:'The Sun Blade is destroyed in the fire.',at:30}).result;assert.equal(learned.events[0].eventType,'FIRE_DESTRUCTION');const causal=learned.relationships.find(r=>r.predicate==='causedDestructionOf');assert.ok(causal);assert.equal(causal.metadata.causal,true);assert.deepEqual(causal.provenance.sourceRevisionIds,['fire:evidence@1']);const claim=learned.claims.find(c=>c.predicate==='state');assert.ok(claim.provenance.derivedFromIds.some(id=>id.startsWith('event:fire:evidence:')));});

test('extended Ember Tavern golden-world scorer keeps history, conflict, provenance, and relearning truthful',()=>{const scored=runWave2EmberTavernGoldenWorld();assert.equal(scored.pass,true,JSON.stringify(scored.metrics,null,2));assert.equal(scored.metrics.tavernDestroyed,true);assert.equal(scored.metrics.bladeUnresolved,true);assert.ok(scored.metrics.conflictingEvidencePaths>=2);assert.equal(scored.metrics.historicalDepositRecovered,true);assert.equal(scored.metrics.temporalChannelCovered,true);assert.equal(scored.metrics.provenanceComplete,true);assert.equal(scored.metrics.unrelatedKnowledgeSurvived,true);assert.equal(scored.metrics.unresolvedAfterRelearn,true);});
test('bounded Reflection proposes inferred learning, admits repeated evidence, and weakens after support changes',()=>{const core=new Area52CognitiveCore();const sources=[['obs1','Mara protects civilians during the riot.',10],['obs2','Mara shields civilians during the raid.',20],['obs3','Mara evacuates civilians before pursuing the attacker.',30]];const evidence=[];for(const [id,content,at] of sources){const learned=core.importAndLearn({id,sourceType:'EXPERIENCE',content,at});evidence.push(learned.result.claims.find(c=>c.predicate==='behavior').id);}const proposal=core.reflection.proposePattern({subjectId:'mara',pattern:{predicate:'trait',value:'prioritizes-civilian-safety'},evidenceClaimIds:evidence,reasoningSummary:'Mara appears to consistently prioritize civilian safety.'});assert.equal(proposal.authorityClass,AuthorityClass.INFERRED);assert.equal(proposal.status,ReflectionStatus.PROPOSED);const decision=core.reflection.settleProposal(proposal.id);assert.equal(decision.status,ReflectionStatus.ADMITTED);const reflection=core.reflection.reflections()[0];assert.equal(reflection.reflectionStatus,ReflectionStatus.ADMITTED);assert.equal(reflection.status,'INFERRED');const edit=core.editAndRelearn('obs2','Mara abandons civilians to pursue the attacker.');const refreshed=edit.reflectionRefresh.find(r=>r.id===reflection.id);assert.equal(refreshed.reflectionStatus,ReflectionStatus.SUPPORTED);const contradictionId=edit.relearned.result.claims.find(c=>c.predicate==='behavior').id;const feedback=core.reflection.applyEvidenceFeedback(reflection.id,{contradictionEvidenceIds:[contradictionId]});assert.equal(feedback.status,ReflectionStatus.UNRESOLVED);});

test('future Scene Intelligence evidence types can enter through a provider-neutral evidence contract',()=>{const core=new Area52CognitiveCore();const out=core.importEvidence({id:'scene:location',evidenceType:EvidenceType.LOCATION_CHANGED,content:'Eris departs the Ember Tavern.',at:12});assert.equal(out.evidence.evidenceType,EvidenceType.LOCATION_CHANGED);assert.equal(core.registry.getSource('scene:location').metadata.evidenceType,EvidenceType.LOCATION_CHANGED);assert.ok(out.learning.result.events.some(e=>e.eventType==='DEPARTURE'));});

test('Settlement Engine exposes the complete Wave 2 decision vocabulary deterministically',()=>{
  const core=new Area52CognitiveCore();
  const first=core.importAndLearn({id:'decision:a',sourceType:'EXPERIENCE',content:'The Relic is intact.',at:0});
  assert.equal(first.decisions.find(d=>d.proposalId.includes('claim:'))?.decision,SettlementDecisionType.ACCEPT_CURRENT);
  const newer=core.importAndLearn({id:'decision:b',sourceType:'EXPERIENCE',content:'The Relic is damaged.',at:10});
  assert.equal(newer.decisions.find(d=>d.proposalId.includes('claim:'))?.decision,SettlementDecisionType.SUPERSEDE);
  const older=core.importAndLearn({id:'decision:c',sourceType:'LORE',content:'The Relic is intact.',at:5});
  assert.equal(older.decisions.find(d=>d.proposalId.includes('claim:'))?.decision,SettlementDecisionType.ACCEPT_HISTORICAL);
  const conflict=core.importAndLearn({id:'decision:d',sourceType:'LORE',content:'A later recovered journal claims the Relic survived the fire.',at:20,metadata:{claimAt:10}});
  assert.equal(conflict.decisions.find(d=>d.decision===SettlementDecisionType.UNRESOLVED)?.decision,SettlementDecisionType.UNRESOLVED);

  core.registry.importSource({id:'decision:inferred',sourceType:'LORE',content:'inference-source',metadata:{at:10}});
  const rev=core.registry.getActiveRevision('decision:inferred');
  const provenance={kind:'Provenance',id:'prov:inferred',sourceRevisionIds:[rev.id],evidenceIds:[],derivedFromIds:[],activity:'TEST',agent:'test',invalidators:[rev.id]};
  const inferredClaim={kind:'Claim',id:'claim:decision:inferred@1:test',subjectId:'relic',predicate:'state',value:'pristine',temporal:{kind:'CURRENT',validFrom:10,validUntil:null},authorityClass:AuthorityClass.INFERRED,confidence:.9,status:'CURRENT',provenance,supersedes:[],contradictedBy:[],owner:'WORLD_STATE',semanticKey:'relic|state|"pristine"',stableIdentity:'stable:pristine',claimType:'STATE',slotPolicy:'SINGLE',explicitness:'INFERRED',evidenceTime:10};
  core.registry.registerDerivedArtifact({artifactId:inferredClaim.id,artifact:inferredClaim,sourceRevisionIds:[rev.id],activity:'TEST',agent:'test'});
  const proposal={kind:'MutationProposal',id:'proposal:inferred-conflict',mutationType:'SET_CLAIM',owner:'WORLD_STATE',sourceRevisionIds:[rev.id],evidenceIds:[inferredClaim.id],freshnessRevisionIds:[rev.id],payload:{claim:core.registry.getArtifact(inferredClaim.id)},status:'PROPOSED'};
  assert.equal(core.settlement.settle(proposal).decision.decision,SettlementDecisionType.CONTRADICT);

  const staleProposal=first.result.proposals.find(p=>p.mutationType==='SET_CLAIM');
  core.registry.replaceSource('decision:a','The Relic is repaired.');
  assert.equal(core.settlement.settle(staleProposal).decision.decision,SettlementDecisionType.REJECT);
});
