import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { FrontFaceMode, ProductDetailLevel, UIStateStore, computeVirtualWindow, createWave6ProductInterface } from '../src/ui-core/index.js';
import { FakeDocument, FakeNode } from './fixtures/wave4-synthetic-extension.mjs';
import { createReviewScenarios } from '../demo/phase2-shell/scenarios/index.js';
import { installPhase2ReviewWorkspaces } from '../demo/phase2-shell/review-workspaces.js';
import { REVIEW_LAYOUTS, REVIEW_WIDTHS, createPhase2ReviewController } from '../demo/phase2-shell/app.js';
class Doc extends FakeDocument{createDocumentFragment(){return new FakeNode('fragment',this);}}
class ReviewDoc extends Doc{
  constructor(){
    super();this.bySelector=new Map();
    const add=(id,tag='div',value='')=>{const node=new FakeNode(tag,this);node.id=id;node.value=value;node.checked=false;node.style.setProperty=(name,next)=>{node.style[name]=String(next);};node.style.removeProperty=name=>{delete node.style[name];};this.bySelector.set(`#${id}`,node);this.body.append(node);return node;};
    add('area52-phase2-root');add('phase2-review-frame');add('phase2-host-surface');add('review-fixture-label');add('review-scenario-description');
    add('review-scenario','select','healthy');add('review-detail','select','NORMAL');add('review-layout','select','desktop');add('review-width','select','w720');add('review-inspector','input');add('review-reset','button');
  }
  querySelector(selector){return this.bySelector.get(selector)??null;}
}
const memory=()=>{const m=new Map();return{getItem:k=>m.get(k)??null,setItem:(k,v)=>m.set(k,String(v)),removeItem:k=>m.delete(k),m};};
const textOf=node=>[node?.textContent??'',...(node?.children??[]).map(textOf)].filter(Boolean).join(' ');
function mountScenario(id='healthy'){const rec=createReviewScenarios().get(id),doc=new Doc(),root=new FakeNode('div',doc),stateStore=new UIStateStore({storage:memory(),namespace:`wave9:${id}`});const ui=createWave6ProductInterface({root,stateStore,fixture:rec.product,bridges:{cognition:rec.cognition?{fixture:rec.cognition}:{}}});installPhase2ReviewWorkspaces(ui);ui.presentation.patch({frontFaceMode:FrontFaceMode.EXPANDED,frontFaceWidth:720});ui.productAdapter.setDetailLevel(ProductDetailLevel.NORMAL);ui.shell.selectWorkspace('home');ui.scheduler.flush(0);return{rec,doc,root,ui};}
test('Wave 9 exposes exactly the six review scenarios and all are explicit FIXTURE records',()=>{const s=createReviewScenarios();assert.deepEqual([...s.keys()],['healthy','hot-only','retrieval-heavy','ambiguous','degraded','empty']);for(const x of s.values())assert.equal(x.mode,'FIXTURE');});
test('Ember Tavern world is coherent across Scene, Lore, World and Brain cognition',()=>{const s=createReviewScenarios().get('ambiguous');assert.equal(s.product.scene.title,'Ember Tavern');assert.ok(s.product.lore.entries.some(x=>x.title==='Sun Blade'));assert.equal(s.product.world.entities.find(x=>x.id==='ember-tavern').current,'Destroyed');assert.equal(s.product.world.entities.find(x=>x.id==='sun-blade').current,'Unknown');assert.equal(s.cognition.jev.outcome,'ABSTAINED');assert.equal(s.cognition.jev.requiresOwnerSettlement,true);});
test('Hot-only scenario visibly skips unnecessary retrieval/Jev/Precision',()=>{const c=createReviewScenarios().get('hot-only').cognition.cognitiveChoiceReceipt;assert.equal(c.retrievalDecision.status,'SKIPPED');assert.equal(c.jevDecision.status,'SKIPPED');assert.equal(c.precisionDecision.status,'SKIPPED');});
test('Degraded scenario contains stale, late and malformed work while preserving a sealed result',()=>{const c=createReviewScenarios().get('degraded').cognition;assert.ok(c.gather.results.some(x=>x.status==='STALE'));assert.ok(c.gather.results.some(x=>x.status==='LATE'));assert.ok(c.gather.results.some(x=>x.status==='INVALID'));assert.equal(c.seal.sealedState,true);assert.equal(c.seal.admittedResultIds.length,1);});
test('Empty scenario does not fabricate Scene, Lore, Memory or World state',()=>{const p=createReviewScenarios().get('empty').product;assert.equal(p.scene,null);assert.equal(p.lore.count,0);assert.equal(p.memory.experiences,0);assert.equal(p.world.entities.length,0);});
test('review shell uses repository-relative static assets and labels host/fixture boundaries',async()=>{const html=await readFile(new URL('../demo/phase2-shell/index.html',import.meta.url),'utf8');assert.match(html,/DEMO \/ FIXTURE DATA/);assert.match(html,/HOST-OWNED SURFACE/);assert.match(html,/\.\.\/\.\.\/styles\/ui-core\.css/);assert.match(html,/type="module" src="\.\/app\.js"/);assert.doesNotMatch(html,/message-bubble|chat-message|send-message/i);});
test('review controls expose required disclosure, responsive and width presets',()=>{assert.deepEqual(Object.keys(REVIEW_LAYOUTS),['wide','desktop','compact','narrow']);assert.deepEqual(Object.values(REVIEW_WIDTHS),[76,420,560,720,900]);});
test('Phase-2 workspaces reuse the existing WorkspaceRegistry and product navigation IDs',()=>{const{ui}=mountScenario();for(const id of ['home','story','characters','lore','memory-product','world-product','brain'])assert.ok(ui.workspaceRegistry.has(id));assert.equal(ui.workspaceRegistry.list({navigationLevel:'product'}).length,7);ui.destroy();});
test('Home is product-facing and not a metrics dump',()=>{const{ui}=mountScenario();const t=textOf(ui.shell.nodes.workspace);for(const label of ['Story Now','Brain Status','World','Lore','Memory','Context','Attention'])assert.match(t,new RegExp(label));assert.doesNotMatch(t,/queue depth|worker id|model id/i);ui.destroy();});
test('Story normal/detail/advanced disclosure progressively exposes Scene evidence',()=>{const{ui}=mountScenario();ui.shell.selectWorkspace('story');ui.scheduler.flush(1);assert.match(textOf(ui.shell.nodes.workspace),/Ember Tavern/);ui.productAdapter.setDetailLevel('DETAIL');ui.shell.refreshCurrentWorkspace();assert.match(textOf(ui.shell.nodes.workspace),/Observed cast|Boundary/);ui.productAdapter.setDetailLevel('ADVANCED');ui.shell.refreshCurrentWorkspace();assert.match(textOf(ui.shell.nodes.workspace),/Scene ID/);ui.destroy();});
test('Character shell explicitly separates belief from world truth',()=>{const{ui}=mountScenario();ui.shell.selectWorkspace('characters');assert.match(textOf(ui.shell.nodes.workspace),/Character belief is not world truth/);assert.match(textOf(ui.shell.nodes.workspace),/Personal memory/);ui.destroy();});
test('Lore, Memory and World review shells expose required product distinctions',()=>{const{ui}=mountScenario();ui.shell.selectWorkspace('lore');assert.match(textOf(ui.shell.nodes.workspace),/Lore Browser \/ Tree/);assert.match(textOf(ui.shell.nodes.workspace),/Learned Status/);ui.shell.selectWorkspace('memory-product');assert.match(textOf(ui.shell.nodes.workspace),/Experience/);assert.match(textOf(ui.shell.nodes.workspace),/Reflection/);ui.shell.selectWorkspace('world-product');assert.match(textOf(ui.shell.nodes.workspace),/Unresolved conflict/);assert.match(textOf(ui.shell.nodes.workspace),/Unknown/);ui.destroy();});
test('Brain remains the Wave 8 cognition workspace and fixture provenance stays explicit',()=>{const{ui}=mountScenario('ambiguous');ui.shell.selectWorkspace('brain');ui.scheduler.flush(1);const t=textOf(ui.shell.nodes.workspace);assert.match(t,/Cognitive|Jev|Gather|Context Seal/);assert.match(t,/FIXTURE/i);ui.destroy();});
test('Inspector uses the existing InspectorController and can inspect review objects',()=>{const{ui}=mountScenario();const before=ui.inspectorRegistry.list().length;ui.signals.publish('UI_INSPECT_SELECTION_CHANGED',{object:{kind:'framework-artifact',id:'sun-blade',title:'Sun Blade',authority:'UNRESOLVED',payload:{state:'Unknown'}}},{source:'wave9-test'});ui.scheduler.flush(1);assert.equal(ui.shell.inspector.selection.id,'sun-blade');assert.equal(ui.inspectorRegistry.list().length,before);ui.destroy();});
test('Front Face presentation accepts collapsed and 420/560/720/900 review widths',()=>{const{ui}=mountScenario();ui.presentation.patch({frontFaceMode:FrontFaceMode.COLLAPSED});assert.equal(ui.presentation.get().frontFaceMode,'COLLAPSED');for(const width of [420,560,720,900]){ui.presentation.patch({frontFaceMode:FrontFaceMode.EXPANDED,frontFaceWidth:width});assert.equal(ui.presentation.get().frontFaceWidth,width);}ui.destroy();});
test('large review collections remain bounded by canonical virtualization math',()=>{for(const count of [10000,20000]){const w=computeVirtualWindow({count,itemSize:48,viewportSize:480,scrollOffset:240000,overscan:8});assert.ok(w.end-w.start<=26);}});
test('destroy removes UI listeners and root content cleanly',()=>{const{ui,root}=mountScenario();ui.destroy();assert.equal(ui.signals.listenerCount('UI_WORKSPACE_CHANGED'),0);assert.equal(ui.signals.listenerCount('UI_INSPECT_SELECTION_CHANGED'),0);assert.equal(ui.signals.listenerCount('*'),0);assert.equal(root.children.length,0);});
test('review controller destroy removes toolbar and document listeners before clean remount',()=>{
  const doc=new ReviewDoc(),storage=memory(),bindings=[['#review-scenario','change'],['#review-detail','change'],['#review-layout','change'],['#review-width','change'],['#review-inspector','change'],['#review-reset','click']];
  const mountedCounts=()=>({keydown:doc.listeners.get('keydown')?.size??0,controls:bindings.map(([selector,event])=>doc.querySelector(selector).listeners.get(event)?.size??0)});
  const assertClean=()=>{assert.equal(doc.listeners.get('keydown')?.size??0,0);for(const [selector,event] of bindings)assert.equal(doc.querySelector(selector).listeners.get(event)?.size??0,0,`${selector} ${event} listener leaked`);};
  let controller=createPhase2ReviewController({document:doc,storage});const first=mountedCounts();assert.ok(first.keydown>0);assert.deepEqual(first.controls,[1,1,1,1,1,1]);controller.destroy();assertClean();
  controller=createPhase2ReviewController({document:doc,storage});assert.deepEqual(mountedCounts(),first);controller.destroy();assertClean();
});
test('Wave 9 docs keep #224 live binding pending rather than claiming Phase 2 complete',async()=>{const doc=await readFile(new URL('../docs/UI_CORE_WAVE_9_PHASE2_DEMO_SHELL.md',import.meta.url),'utf8');assert.match(doc,/LIVE #224 BINDING PENDING/);assert.doesNotMatch(doc,/Phase 2 complete/i);});
