import assert from 'node:assert/strict';
import { FrontFaceMode, ProductDetailLevel, UIStateStore, computeVirtualWindow, createWave6ProductInterface } from '../src/ui-core/index.js';
import { FakeDocument, FakeNode } from './fixtures/wave4-synthetic-extension.mjs';
import { wave8LargeFixture } from './fixtures/wave8-cognition-fixtures.mjs';
import { createReviewScenarios } from '../demo/phase2-shell/scenarios/index.js';
import { installPhase2ReviewWorkspaces } from '../demo/phase2-shell/review-workspaces.js';
import { REVIEW_LAYOUTS, REVIEW_WIDTHS } from '../demo/phase2-shell/app.js';
class Doc extends FakeDocument{createDocumentFragment(){return new FakeNode('fragment',this);}}
const memory=()=>{const m=new Map();return{getItem:k=>m.get(k)??null,setItem:(k,v)=>m.set(k,String(v)),removeItem:k=>m.delete(k),m};};
const countNodes=node=>1+(node?.children??[]).reduce((n,x)=>n+countNodes(x),0);const clone=x=>structuredClone(x);const scenarios=createReviewScenarios(),base=clone(scenarios.get('retrieval-heavy').product),largeProduct=clone(base);
largeProduct.lore.entries=Array.from({length:10000},(_,i)=>({id:`lore:${i}`,title:`Lore ${i}`,source:`Source ${i}`,entities:['Mara'],claims:[`Claim ${i}`],relationships:[],representations:['review'],authority:i%97===0?'UNRESOLVED':'SOURCE_CANON',revision:'r6'}));largeProduct.lore.count=10000;largeProduct.memory.episodes=Array.from({length:10000},(_,i)=>({id:`memory:${i}`,label:`Memory ${i}`,kind:i%3===0?'EPISODE':i%3===1?'EXPERIENCE':'REFLECTION',state:i%97===0?'UNRESOLVED':i%2?'CURRENT':'HISTORICAL',summary:`Review memory ${i}`}));largeProduct.memory.experiences=10000;
const cognition=clone(scenarios.get('retrieval-heavy').cognition),largeCognition=wave8LargeFixture(10000),doc=new Doc(),root=new FakeNode('div',doc),storage=memory(),stateStore=new UIStateStore({storage,namespace:'wave9-stress'});let ui=createWave6ProductInterface({root,stateStore,fixture:base,bridges:{cognition:{fixture:cognition}}});installPhase2ReviewWorkspaces(ui);ui.presentation.patch({frontFaceMode:FrontFaceMode.EXPANDED,frontFaceWidth:720});ui.productAdapter.setDetailLevel(ProductDetailLevel.ADVANCED);ui.shell.selectWorkspace('brain');ui.scheduler.flush(0);
for(let i=0;i<1000;i++)ui.presentation.patch({frontFaceMode:i%2?FrontFaceMode.EXPANDED:FrontFaceMode.COLLAPSED,frontFaceWidth:[420,560,720,900][i%4]});for(let i=0;i<600;i++){ui.productAdapter.setDetailLevel([ProductDetailLevel.NORMAL,ProductDetailLevel.DETAIL,ProductDetailLevel.ADVANCED][i%3]);ui.shell.refreshCurrentWorkspace();}const workspaces=['home','story','characters','lore','memory-product','world-product','brain'];for(let i=0;i<700;i++)ui.shell.selectWorkspace(workspaces[i%workspaces.length]);for(let i=0;i<500;i++){ui.shell.inspector.select({kind:'framework-artifact',id:`review:${i}`,title:`Review ${i}`,authority:'OBSERVED',payload:{revision:i}});ui.shell.inspector.clear();}for(let i=0;i<500;i++)ui.presentation.setInspector(i%2===0,240+(i%8)*40);for(let i=0;i<500;i++)ui.presentation.patch({frontFaceMode:FrontFaceMode.EXPANDED,frontFaceWidth:Object.values(REVIEW_WIDTHS).filter(x=>x>76)[i%4]});for(let i=0;i<400;i++){const layout=Object.keys(REVIEW_LAYOUTS)[i%4];assert.ok(REVIEW_LAYOUTS[layout]>=680);}
const largeProductRoot=new FakeNode('div',doc),largeProductUi=createWave6ProductInterface({root:largeProductRoot,stateStore:new UIStateStore({storage:memory(),namespace:'wave9-large-product'}),fixture:largeProduct,bridges:{cognition:{fixture:cognition}}});installPhase2ReviewWorkspaces(largeProductUi);largeProductUi.presentation.patch({frontFaceMode:FrontFaceMode.EXPANDED,frontFaceWidth:900});largeProductUi.productAdapter.setDetailLevel(ProductDetailLevel.ADVANCED);largeProductUi.shell.selectWorkspace('lore');largeProductUi.scheduler.flush(1);const loreNodes=countNodes(largeProductRoot);assert.ok(loreNodes<1200,`large Lore DOM must stay bounded, got ${loreNodes}`);largeProductUi.shell.selectWorkspace('memory-product');largeProductUi.scheduler.flush(2);const memoryNodes=countNodes(largeProductRoot);assert.ok(memoryNodes<1200,`large Memory DOM must stay bounded, got ${memoryNodes}`);largeProductUi.destroy();assert.equal(largeProductRoot.children.length,0);const largeRoot=new FakeNode('div',doc),largeUi=createWave6ProductInterface({root:largeRoot,stateStore:new UIStateStore({storage:memory(),namespace:'wave9-large'}),fixture:base,bridges:{cognition:{fixture:largeCognition}}});installPhase2ReviewWorkspaces(largeUi);largeUi.presentation.patch({frontFaceMode:FrontFaceMode.EXPANDED,frontFaceWidth:900});largeUi.productAdapter.setDetailLevel(ProductDetailLevel.ADVANCED);largeUi.shell.selectWorkspace('brain');largeUi.scheduler.flush(3);const brainNodes=countNodes(largeRoot);assert.ok(brainNodes<1500,`large cognition DOM must stay bounded, got ${brainNodes}`);largeUi.destroy();assert.equal(largeRoot.children.length,0);const largeWindow=computeVirtualWindow({count:10000,itemSize:48,viewportSize:480,scrollOffset:240000,overscan:8});assert.ok(largeWindow.end-largeWindow.start<=26);const pendingBefore=ui.scheduler.pendingCount;assert.ok(pendingBefore<=4,'review interactions must keep scheduler work bounded');ui.scheduler.flush(4);
const persisted=ui.presentation.get();ui.destroy();assert.deepEqual({workspace:ui.signals.listenerCount('UI_WORKSPACE_CHANGED'),inspect:ui.signals.listenerCount('UI_INSPECT_SELECTION_CHANGED'),wildcard:ui.signals.listenerCount('*')},{workspace:0,inspect:0,wildcard:0});assert.equal(root.children.length,0);
let scenarioRemounts=0;for(let round=0;round<10;round++)for(const rec of scenarios.values()){const r=new FakeNode('div',doc),scenarioState=new UIStateStore({storage:memory(),namespace:`wave9-scenario-${round}-${rec.id}`}),next=createWave6ProductInterface({root:r,stateStore:scenarioState,fixture:rec.product,bridges:{cognition:rec.cognition?{fixture:rec.cognition}:{}}});installPhase2ReviewWorkspaces(next);next.presentation.patch({frontFaceMode:FrontFaceMode.EXPANDED,frontFaceWidth:560});next.shell.selectWorkspace(round%2?'brain':'home');next.scheduler.flush(round);next.destroy();assert.equal(r.children.length,0);assert.equal(next.signals.listenerCount('*'),0);scenarioRemounts++;}
const restoredRoot=new FakeNode('div',doc);ui=createWave6ProductInterface({root:restoredRoot,stateStore,fixture:base,bridges:{cognition:{fixture:cognition}}});installPhase2ReviewWorkspaces(ui);assert.deepEqual(ui.presentation.get(),persisted);ui.destroy();
console.log(JSON.stringify({collapseExpandCycles:1000,detailLevelSwitches:600,workspaceSwitches:700,inspectorCycles:500,inspectorVisibilityChanges:500,widthChanges:500,responsivePresetChanges:400,scenarioRemounts,largeLoreEntries:10000,largeMemoryRecords:10000,largeCandidateCount:10000,largeGatherResultCount:10000,virtualMountedWindow:largeWindow.end-largeWindow.start,loreDomNodes:loreNodes,memoryDomNodes:memoryNodes,brainDomNodes:brainNodes,schedulerPendingBeforeFlush:pendingBefore,listenersAfterDestroy:{workspace:0,inspect:0,wildcard:0},rootChildrenAfterDestroy:0,presentationRestored:true},null,2));
