import { PromptSlot,ContributionSource,ReuseState,RepresentationMode,DeliveryStatus,createPromptPlan,deliveryHash } from './adaptive-context-contracts.js';
import { PromptSlotRegistry,ModelProfileRegistry } from './adaptive-context-slots.js';
import { DeterministicApproxTokenEstimator,AdaptiveBudgetAllocator } from './adaptive-context-budget.js';
import { packetFactMap,sectionFromFacts,sectionFromContribution,orderSections } from './adaptive-context-sections.js';
import { buildSegments } from './adaptive-context-segments.js';
import { PromptIntegrityGuard } from './prompt-integrity-guard.js';
const uniq=(values)=>[...new Set(values)].sort();
function deepFreeze(value){if(!value||typeof value!=='object'||Object.isFrozen(value))return value;Object.freeze(value);for(const key of Object.keys(value))deepFreeze(value[key]);return value;}

export class PromptPlanner{
  constructor({slotRegistry=new PromptSlotRegistry(),profileRegistry=new ModelProfileRegistry(),estimator=new DeterministicApproxTokenEstimator(),integrityGuard=new PromptIntegrityGuard(),deliveryLearning=null}={}){this.slotRegistry=slotRegistry;this.profileRegistry=profileRegistry;this.estimator=estimator;this.integrityGuard=integrityGuard;this.deliveryLearning=deliveryLearning;this.allocator=new AdaptiveBudgetAllocator({estimator});}
  createPlan({sealedPacket,sealReceipt,generationId,turnId=sealReceipt?.turnId,modelProfileId='CACHE_STABLE',fallbackProfileId=null,intent=sealedPacket?.intent??'CURRENT',budgetTokens=null,systemPolicy=null,userInput=null,contributions=[],previousPlan=null,worldRevision=sealReceipt?.worldRevision??0,sceneRevision=sealReceipt?.sceneRevision??0}){
    if(!sealedPacket||!sealReceipt)throw new TypeError('sealedPacket and sealReceipt are required');
    const resolved=this.profileRegistry.resolve(modelProfileId,{fallbackProfileId});if(!resolved.profile)return{ok:false,status:DeliveryStatus.PROFILE_UNAVAILABLE,failure:{code:'MODEL_PROFILE_UNAVAILABLE',modelProfileId},plan:null};
    const learned=this.deliveryLearning?.applyToProfile?.(resolved.profile)??{profile:resolved.profile,policy:null},profile=learned.profile,fallbackDecisions=[];if(resolved.fallbackUsed)fallbackDecisions.push(`PROFILE_FALLBACK:${modelProfileId}->${profile.modelProfileId}`);if(learned.policy)fallbackDecisions.push(`DELIVERY_POLICY:${learned.policy.policyId}`);if(profile.tokenEstimatorId!==this.estimator.id)fallbackDecisions.push(`TOKEN_ESTIMATOR_FALLBACK:${profile.tokenEstimatorId}->${this.estimator.id}`);
    const normalized=[];
    try{for(const contribution of contributions)normalized.push(this.slotRegistry.normalizeContribution(contribution));if(systemPolicy!==null)normalized.push(this.slotRegistry.normalizeContribution({id:`policy:${deliveryHash(systemPolicy).slice(0,12)}`,slot:PromptSlot.SYSTEM_POLICY,sourceCategory:ContributionSource.STATIC_POLICY,owner:'OPERATOR_POLICY',semantic:false,semanticRefs:[],content:systemPolicy,sourceRevisionIds:[],role:'system',required:true,priority:10,metadata:{revision:'explicit'}}));if(userInput!==null)normalized.push(this.slotRegistry.normalizeContribution({id:`user:${deliveryHash(userInput).slice(0,12)}`,slot:PromptSlot.USER_INPUT,sourceCategory:ContributionSource.GENERATION_ENVELOPE,owner:'GENERATION_ENVELOPE',semantic:false,semanticRefs:[],content:userInput,sourceRevisionIds:[],role:'user',required:true,priority:10,metadata:{generationId}}));}
    catch(error){return{ok:false,status:DeliveryStatus.INTEGRITY_REJECTED,failure:{code:String(error.message||error)},plan:null};}
    const sections=[];if((sealedPacket.current??[]).length)sections.push(sectionFromFacts(sealedPacket,PromptSlot.CURRENT_WORLD_STATE,sealedPacket.current,this.slotRegistry.get(PromptSlot.CURRENT_WORLD_STATE),{priority:9}));if((sealedPacket.historical??[]).length)sections.push(sectionFromFacts(sealedPacket,PromptSlot.HISTORICAL_SUPPORT,sealedPacket.historical,this.slotRegistry.get(PromptSlot.HISTORICAL_SUPPORT),{priority:6}));if((sealedPacket.unresolved??[]).length)sections.push(sectionFromFacts(sealedPacket,PromptSlot.UNRESOLVED_EVIDENCE,sealedPacket.unresolved,this.slotRegistry.get(PromptSlot.UNRESOLVED_EVIDENCE),{priority:10}));if((sealedPacket.activeThreads??[]).length)sections.push(sectionFromFacts(sealedPacket,PromptSlot.ACTIVE_THREADS,sealedPacket.activeThreads,this.slotRegistry.get(PromptSlot.ACTIVE_THREADS),{priority:10}));
    const facts=packetFactMap(sealedPacket);
    for(const contribution of normalized){const spec=this.slotRegistry.get(contribution.slot);if(contribution.sourceCategory===ContributionSource.SEALED_PACKET){const selected=[];for(const ref of contribution.semanticRefs){const row=facts.get(ref);if(!row)return{ok:false,status:DeliveryStatus.INTEGRITY_REJECTED,failure:{code:'SEALED_REFERENCE_NOT_FOUND',ref,contributionId:contribution.id},plan:null};selected.push(row.fact);}sections.push(sectionFromFacts(sealedPacket,contribution.slot,selected,spec,{priority:contribution.priority}));}else sections.push(sectionFromContribution(contribution,spec,contribution.content));}
    const mergedBySlot=new Map();
    for(const section of sections){const existing=mergedBySlot.get(section.slot);if(!existing){mergedBySlot.set(section.slot,section);continue;}if(existing.owner!==section.owner||existing.role!==section.role)return{ok:false,status:DeliveryStatus.INTEGRITY_REJECTED,failure:{code:'CONFLICTING_SLOT_OWNERSHIP',slot:section.slot},plan:null};const content=[...(Array.isArray(existing.content)?existing.content:[existing.content]),...(Array.isArray(section.content)?section.content:[section.content])];const rendered=typeof content==='string'?{richText:content,compactText:content}:{richText:`${section.slot}\n${JSON.stringify(content,null,2)}`,compactText:JSON.stringify(content)};mergedBySlot.set(section.slot,{...existing,content,...rendered,protected:existing.protected||section.protected,priority:Math.max(existing.priority,section.priority),sourceRevisionIds:uniq([...existing.sourceRevisionIds,...section.sourceRevisionIds]),semanticManifest:[...existing.semanticManifest,...section.semanticManifest],sourceCategory:existing.sourceCategory??section.sourceCategory});}
    let ordered=orderSections([...mergedBySlot.values()],profile);const allocation=this.allocator.allocate({sections:ordered,profile,intent,userInput:userInput??'',budgetTokens});if(!allocation.ok)return{ok:false,status:allocation.status,failure:{code:allocation.status,budget:allocation.budget},budget:allocation.budget,plan:null};fallbackDecisions.push(...allocation.fallbackDecisions);
    ordered=allocation.sections.map(section=>{const omitted=section.representation===RepresentationMode.OMITTED,text=omitted?'':section.representation===RepresentationMode.RICH?section.richText:section.compactText,semanticManifest=omitted?[]:section.semanticManifest;return{...section,content:omitted?null:section.content,richText:omitted?'':section.richText,compactText:omitted?'':section.compactText,semanticManifest,text,sectionIdentity:deliveryHash({slot:section.slot,representation:section.representation,manifest:semanticManifest,sourceRevisionIds:section.sourceRevisionIds,text})};});
    const segments=buildSegments(ordered,profile,previousPlan),reuseDecisions=[...segments.map(s=>({segmentKey:s.segmentKey,state:s.reuseState,changedSlots:s.changedSlots})),...allocation.dropped.map(x=>({segmentKey:`slot:${x.slot}`,state:ReuseState.OMIT,changedSlots:[]})),...allocation.deferred.map(x=>({segmentKey:`slot:${x.slot}`,state:ReuseState.OMIT,changedSlots:[]}))],cacheDecisions=segments.map(s=>({segmentId:s.segmentId,segmentKey:s.segmentKey,cacheEligible:s.cacheEligible,cacheKey:s.cacheKey,reuseState:s.reuseState,invalidators:s.sourceRevisionIds})),semanticManifest=ordered.flatMap(s=>s.semanticManifest??[]);
    const promptPlanId=`prompt-plan:${deliveryHash({generationId,turnId,seal:sealReceipt.id,packetHash:sealReceipt.packetHash,profile:profile.modelProfileId,profileRevision:profile.revision,policy:profile.deliveryPolicyRevision,sections:ordered.map(s=>[s.slot,s.sectionIdentity]),previousPromptPlanId:previousPlan?.promptPlanId??null}).slice(0,24)}`;
    const diagnosticReceipt={estimator:{id:this.estimator.id,exact:Boolean(this.estimator.exact)},neutralSizing:structuredClone(sealedPacket.semanticSizing??null),deliveryPolicy:learned.policy?{policyId:learned.policy.policyId,version:learned.policy.version,status:learned.policy.status}:null,profileFallbackUsed:resolved.fallbackUsed,segmentStrategy:profile.segmentStrategy,semanticManifestHash:deliveryHash(semanticManifest),semanticEntryCount:semanticManifest.length,sectionCount:ordered.length,segmentCount:segments.length,reuse:{noChange:segments.filter(s=>s.reuseState===ReuseState.NO_CHANGE).length,patch:segments.filter(s=>s.reuseState===ReuseState.PATCH).length,rebuild:segments.filter(s=>s.reuseState===ReuseState.REBUILD).length,omit:allocation.dropped.length}};if(sealedPacket.hotCognitionSnapshotId)diagnosticReceipt.hotCognition={snapshotId:sealedPacket.hotCognitionSnapshotId,hotRevision:sealedPacket.hotCognitionRevision,chatNamespace:sealedPacket.hotCognitionChatNamespace};
    const plan=createPromptPlan({promptPlanId,generationId,turnId,contextSealId:sealReceipt.id,sealedPacketHash:sealReceipt.packetHash,modelProfileId:profile.modelProfileId,modelProfileRevision:profile.revision,deliveryPolicyRevision:profile.deliveryPolicyRevision,sections:ordered,segments,budget:allocation.budget,ordering:ordered.filter(s=>s.representation!==RepresentationMode.OMITTED).map(s=>s.slot),placement:{segmentStrategy:profile.segmentStrategy,bands:segments.map(s=>s.band)},reuseDecisions,cacheDecisions,fallbackDecisions,dropped:allocation.dropped,deferred:allocation.deferred,sourceRevisionDependencies:uniq(sealReceipt.sourceRevisionIds??sealedPacket.dependencies??[]),worldRevision,sceneRevision,diagnosticReceipt,previousPromptPlanId:previousPlan?.promptPlanId??null,status:DeliveryStatus.READY});
    const integrityReceipt=this.integrityGuard.validatePlan({plan,sealedPacket,sealReceipt});if(!integrityReceipt.valid)return{ok:false,status:DeliveryStatus.INTEGRITY_REJECTED,failure:{code:'PROMPT_INTEGRITY_REJECTED',violations:integrityReceipt.violations},plan,integrityReceipt};return{ok:true,status:DeliveryStatus.READY,plan:deepFreeze(plan),integrityReceipt,profile};
  }
}
